grid: CorrectedPhenobench
# --- parameters
test:
  prompt_to_use: [null] # How many prompt use in testing - null => all
dataloader:
  num_workers: [0]
dataset:
  preprocess:
    mean: [[0.485, 0.456, 0.406]]
    std: [[0.229, 0.224, 0.225]]
    image_size: &image_size [384]
  datasets:
    test_phenobench:
      root: ["../Datasets/PhenoBench"]
      prompt_images:
        -
          - 167
          - 1110
          - 1272
          - 879
tracker:
  project: [FSSWeed]
  group: [PhenoBench]
  log_frequency: [1]
  tags: [[PhenoBench]]
  tmp_dir: [tmp]
  train_image_log_frequency: [25]
  test_image_log_frequency: [10]
  wandb:
    entity: [pasqualedem]
    offline: [false]
    tags: [PhenoBench]
model:
  name: [weeddcama]
  backbone: [swin]
  backbone_checkpoint: [checkpoints/swin_base_patch4_window12_384.pth]
  model_checkpoint: [checkpoints/swin_fold0_pascal_modcross_soft.pt]
  concat_support: [false]
  image_size: *image_size
refinement:
  lr: [1.e-3]
  max_iterations: [1000, 2000]
  hot_parameters:
    -
      - "model_0.conv1"
      - "model_0.conv2"
      - "model_0.conv3"
      - "model_0.mixer1"
      - "model_0.mixer2"
      - "model_0.mixer3"
      - "model_1.conv1"
      - "model_1.conv2"
      - "model_1.conv3"
      - "model_1.mixer1"
      - "model_1.mixer2"
      - "model_1.mixer3"
  subsample: [1]
  loss:
    name: [focal]
    gamma: [2]

  