grid: DistillINSID3Industrial
parameters:
  test:
    prompt_to_use: [null]
  dataloader:
    num_workers: [0]
  dataset:
    preprocess:
      mean:
      - [0.485, 0.456, 0.406]
      std:
      - [0.229, 0.224, 0.225]
      image_size: [1024]
    datasets:
      test_industrial:
        datapath: [data]
        fold: [0, 1, 2, 3]
        prompt_images: [10, 20, 40, 80]
  tracker:
    project: [FSSWeed]
    group: [Industrial]
    log_frequency: [1]
    tags:
    - [Industrial, Distill]
    tmp_dir: [tmp]
    cache_dir: [tmp]
    train_image_log_frequency: [25]
    test_image_log_frequency: [10]
    # mode: [offline]
  model:
    name: [distillator]
    params:
      teacher:
        name: [insid3]
        differentiable: [true]
        adapter: [conv]
      student:
        name: [insid3_distillator]
        num_classes: [5]
  refinement:
    lr: [0.001]
    max_iterations: [500]
    hot_parameters:
      - [student, adapter]
    subsample: [3]
    substitutor: [paired]
    iterations_is_num_classes: [false]
    loss:
      name: [refine_distill]
    validate_every: [50]
