grid: DistillINSID3WeedMap5shot_fix
parameters:
  device: [cuda:2]
  test:
    prompt_to_use: [null]
  dataloader:
    num_workers: [0]
  dataset:
    preprocess:
      mean: [[0.485, 0.456, 0.406]]
      std: [[0.229, 0.224, 0.225]]
      image_size: &image_size [1024]
    datasets:
      test_weedmap:
        train_root: [data/weedmap/0_rotations_processed_003_test/RedEdge/000]
        test_root: [data/weedmap/0_rotations_processed_003_test/RedEdge/003]
        prompt_images:
          - 5
        remove_black_images: [false]
  tracker:
    project: [FSSWeed]
    group: [WeedMap]
    log_frequency: [1]
    tags: [[WeedMap, Distill, 5shot]]
    tmp_dir: [tmp]
    cache_dir: [tmp]
    train_image_log_frequency: [null]
    test_image_log_frequency: [null]
    mode: [offline]
  model:
    name: [distillator]
    params:
      teacher:
        name: [insid3]
        differentiable: [true]
        adapter: [conv]
      student:
        name: [insid3_distillator]
        num_classes: [2]
  refinement:
    lr: [1.e-3]
    max_iterations: [500]
    hot_parameters:
      - [student, adapter]
    subsample: [1]
    substitutor: [paired]
    iterations_is_num_classes: [false]
    loss:
      name: [refine_distill]
