dataloader:
  num_workers: 0
dataset:
  preprocess:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    image_size: &image_size 400
  datasets:
    test_weedmap:
      train_root: ../Datasets/WeedMap/0_rotations_processed_003_test/RedEdge/000
      test_root: ../Datasets/WeedMap/0_rotations_processed_003_test/RedEdge/003
      prompt_images: [
              # List of selected images from the training set
              # "frame0009_2.png",
              "frame0021_2.png",
              "frame0033_3.png",
              "frame0034_1.png",
              "frame0048_0.png",
              # "frame0048_1.png",
              # "frame0049_0.png",
              # "frame0073_3.png",
              # "frame0183_1.png",
              # "frame0157_3.png",
              # "frame0197_0.png",
          ]
      remove_black_images: false
tracker:
  project: FFSS
  group: WeedMap
  log_frequency: 1
  tags:
  - Test
  tmp_dir: tmp
  train_image_log_frequency: 25
  test_image_log_frequency: 10
  wandb:
    entity: pasqualedem
    offline: false
model:
  name: 'dmtnet'
  model_checkpoint: 'checkpoints/dmtnet.pt'
refinement:
  lr: 1.e-3
  max_iterations: 50
  hot_parameters: null
    - "hpn_learner"
  subsample: 1
  loss:
    name: focal
    gamma: 2

  