grid: WeedMap
parameters:
  test:
    prompt_to_use: [null] # How many prompt use in testing - null => all
  dataloader:
    num_workers: [0]
  dataset:
    preprocess:
      mean: [[0.485, 0.456, 0.406]]
      std: [[0.229, 0.224, 0.225]]
      image_size: &image_size [384]
    datasets:
      test_weedmap:
        train_root: [../Datasets/WeedMap/0_rotations_processed_003_test/RedEdge/000]
        test_root: [../Datasets/WeedMap/0_rotations_processed_003_test/RedEdge/003]
        # prompt_images: [[
        #         # List of selected images from the training set
        #         # "frame0009_2.png", Only weed
        #         "frame0021_2.png",
        #         "frame0033_3.png",
        #         "frame0034_1.png",
        #         "frame0048_0.png",
        #         # "frame0048_1.png",
        #         # "frame0049_0.png",
        #         # "frame0073_3.png",
        #         # "frame0183_1.png",
        #         # "frame0157_3.png",
        #         # "frame0197_0.png",
        #     ]]
        prompt_images:
          - 25
          - 50

        remove_black_images: [false]
  tracker:
    project: [FSSWeed]
    group: [WeedMap]
    log_frequency: [1]
    tags: [[WeedMap]]
    tmp_dir: [tmp]
    train_image_log_frequency: [25]
    test_image_log_frequency: [10]
  model:
    # -
    #   name: dcama
    #   backbone: swin
    #   backbone_checkpoint: checkpoints/swin_base_patch4_window12_384.pth
    #   model_checkpoint: checkpoints/swin_fold0.pt
    #   concat_support: true
    #   image_size: 384
    -
      name: dcama
      backbone: swin
      backbone_checkpoint: checkpoints/swin_base_patch4_window12_384.pth
      model_checkpoint: checkpoints/swin_fold0_pascal_modcross_soft.pt
      concat_support: false
      image_size: 384
      voting: 10
    # - 
    #   name: dcama
    #   backbone: resnet50
    #   backbone_checkpoint: checkpoints/resnet50_a1h-35c100f8.pth
    #   model_checkpoint: checkpoints/resnet50_fold0.pt
    #   image_size: 384
    - 
      name: dcama
      backbone: resnet50
      backbone_checkpoint: checkpoints/resnet50_a1h-35c100f8.pth
      model_checkpoint: checkpoints/resnet50_fold0_pascal_modcross_soft.pt
      concat_support: false
      image_size: 384
      voting: 10
    # - 
    #   name: dcama
    #   backbone: resnet101
    #   backbone_checkpoint: checkpoints/resnet101_a1h-36d3f2aa.pth
    #   model_checkpoint: checkpoints/resnet101_fold0.pt
    #   image_size: 384
  refinement:
    lr: [1.e-3]
    max_iterations: [1000]
    hot_parameters:
      -
        - "model.conv1"
        - "model.conv2"
        - "model.conv3"
        - "model.mixer1"
        - "model.mixer2"
        - "model.mixer3"
      # -
      #   - "model.conv1"
      #   - "model.conv2"
      #   - "model.conv3"
      #   - "model.conv4"
      #   - "model.conv5"
      #   - "model.mixer1"
      #   - "model.mixer2"
      #   - "model.mixer3"
      # - 
      #   - "model.conv1"
      #   - "model.conv2"
      #   - "model.conv3"
      # - null
      - 
        - model.DCAMA_blocks
        - "model.conv1"
        - "model.conv2"
        - "model.conv3"
        - "model.mixer1"
        - "model.mixer2"
        - "model.mixer3"
      -
        - "model.conv1"
        - "model.conv2"
        - "model.conv3"
        - "model.conv4"
        - "model.conv5"
        - "model.mixer1"
        - "model.mixer2"
        - "model.mixer3"
        - model.DCAMA_blocks
    subsample: [8]
    loss:
      name: [focal]
      gamma: [2]

other_grids: